name: Installing via pip and running
run-name: pip install and run
on: [ push, pull_request ]
jobs:
  install-and-run-on-python-3-11:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install autiobooks
        run: python -m pip install autiobooks
  install-and-run-on-python-3-12:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install autiobooks
        run: python -m pip install autiobooks
  install-and-run-on-python-3-10:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install autiobooks
        run: python -m pip install autiobooks

