name: Installing via pip and running
run-name: pip install and run
on: [ push, pull_request ]
jobs:
  install-and-run-on-python-3-11:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install autiobooks
        run: python -m pip install autiobooks
      - name: Download model
        run: |
          wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files/kokoro-v0_19.onnx
          wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files/voices.json
      - name: Check it runs as module
        run: python -m autiobooks --help
      - name: check it runs as script
        run: autiobooks --help
      - name: install ffmpeg
        run: sudo apt-get install ffmpeg
      - name: download test epub
        run: wget https://github.com/daisy/epub-accessibility-tests/releases/download/fundamental-2.0/Fundamental-Accessibility-Tests-Basic-Functionality-v2.0.0.epub
      - name: create audiobook
        run: autiobooks Fundamental-Accessibility-Tests-Basic-Functionality-v2.0.0.epub
      - name: check m4b output file
        run: ls -lah Fundamental-Accessibility-Tests-Basic-Functionality-v2.0.0.m4b
  install-and-run-on-python-3-12:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install autiobooks
        run: python -m pip install autiobooks
      - name: Download model
        run: |
          wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files/kokoro-v0_19.onnx
          wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files/voices.json
      - name: Check it runs as module
        run: python -m autiobooks --help
      - name: check it runs as script
        run: autiobooks --help
  install-and-run-on-python-3-10:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install autiobooks
        run: python -m pip install autiobooks
      - name: Download model
        run: |
          wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files/kokoro-v0_19.onnx
          wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files/voices.json
      - name: Check it runs as module
        run: python -m autiobooks --help
      - name: check it runs as script
        run: autiobooks --help
